### ISSUE TITLE
more than 3 *** still matches the triple asterisc rule

### ISSUE THREAD

**Issue by DavidSnider** [arxanas/lint381#7]
`/***** Island Class *****/` would be flagged.

**Comment by arxanas** [comment]
I believe I considered matching the regex `\b\*\*\*\b` and it did not work for some comments for some reason, but I can check again.

**Comment by arxanas** [comment]
Well literally `\b` doesn't work because `***` is not a word according to the regex rules and the things around it are therefore not word boundaries.

I didn't find any false negatives in the project 2 or 4 starter files that would occur due to the proposed change. You should be able to update to 1.3.7 once it goes through CI.
